LIB=/home/uchida/dbm/neo4j/neo4j-community-1.6/lib
export CLASSPATH=./:$(LIB)/neo4j-kernel-1.6.jar:$(LIB)/geronimo-jta_1.1_spec-1.1.1.jar
neo4j_create.class: neo4j_create.java
	javac neo4j_create.java
clean:
	rm -f *.class
