#! /usr/bin/node

    const { Client } = require('pg')

    const client = new Client({
        user: 'scott',
        host: 'localhost',
        database: 'city',
        password: 'tiger123',
        port: 5432,
    })
    client.connect()

const query = {
    name: 'fetch-sample',
    text: 'SELECT * FROM cities',
}

client.query(query)
    .then(res => {
	for (var it in res.rows)
		{
	row = res.rows[it]
	var str_out = row.id + '\t'
		str_out += row.name + '\t'
		str_out += row.population + '\t'
		str_out += row.date_mod
		console.log (str_out)
		}
        client.end()
    })
    .catch(e => console.error(e.stack))



