html:
	cd sql_files;make
	cd by_language;make
	cd info_language;make
	cd info_data_base;make
clean:
	cd sql_files;make clean
	cd by_language;make clean
	cd info_language;make clean
	cd info_data_base;make clean
