clean:
	cd swipl; make clean;
	cd ocaml; make clean;
	cd go; make clean;
	cd cplus; make clean;
	cd scala; make clean;
	cd groovy; make clean;
	cd boo; make clean;
	cd fsharp; make clean;
	cd csharp; make clean;
	cd D; make clean;
