html:
	cd example_author;make
	cd example_json;make
	cd example_simple;make
	cd sound_koho;make
	cd librivox_read;make
clean:
	cd example_author;make clean
	cd example_json;make clean
	cd example_simple;make clean
	cd sound_koho;make clean
	cd librivox_read;make clean
