html:
	cd example_author;make
	cd example_json;make
	cd example_simple;make
	cd sound_koho;make
	cd file_upload;make
	cd file_upload_multi;make
	cd librivox_read;make
clean:
	cd example_author;make clean
	cd example_json;make clean
	cd example_simple;make clean
	cd sound_koho;make clean
	cd file_upload;make clean
	cd file_upload_multi;make clean
	cd librivox_read;make clean
