<?php
echo "*** generated by prog/example_php.php ***<br />";
date_default_timezone_set('Asia/Tokyo');
echo "<blockquote>";
echo "*** PHP runs on the server.***<p />";
echo date("Y/m/d  G:i") . "<br />";
echo $_SERVER['SERVER_SOFTWARE'] . "<br />";
echo $_SERVER['SERVER_NAME'] . "<br />";
echo $_SERVER['HTTP_USER_AGENT'] . "<br />";
echo $_SERVER['REMOTE_ADDR'] . "<br />";
echo gethostbyaddr ($_SERVER['REMOTE_ADDR']) . "<br />";
echo "</blockquote>";
echo "*** prog/example_php.php *** end ***<br />";
?>
