html:
	cd bash_common/html; make html;
	cd php_common/html; make html;
	cd python_common/html; make html;
	cd jython_common/html; make html;
	cd perl_common/html; make html;
	cd ruby_common/html; make html;
	cd jruby_common/html; make html;
clean:
	cd cplus_common; make clean;
	cd scala_common; make clean;
	cd groovy_common; make clean;
	cd java_common; make clean;
	cd fsharp_common; make clean;
	cd csharp_common; make clean;
