html:
	cd jquery_only; make html;
	cd jquery_demo; make html;
	cd jquery_bash; make html;
	cd jquery_php; make html;
	cd jquery_python; make html;
	cd jquery_perl; make html;
	cd jquery_ruby; make html;
	cd jquery_lua; make html;
	cd jquery_tcl; make html;
	cd jquery_haskell; make html;
clean:
	cd jquery_only; make clean;
	cd jquery_demo; make clean;
	cd jquery_bash; make clean;
	cd jquery_php; make clean;
	cd jquery_python; make clean;
	cd jquery_perl; make clean;
	cd jquery_ruby; make clean;
	cd jquery_lua; make clean;
	cd jquery_tcl; make clean;
	cd jquery_haskell; make clean;
	cd examples; make clean;
