clean:
	cd haxe; make clean;
	cd kaya; make clean;
	cd ocaml; make clean;
	cd cplus; make clean;
	cd vala; make clean;
	cd cython; make clean;
	cd scala; make clean;
	cd groovy; make clean;
	cd java; make clean;
	cd boo; make clean;
	cd fsharp; make clean;
	cd csharp; make clean;
	cd falcon; make clean;
